### ISSUE TITLE
Enby speakers

### ISSUE THREAD

**Issue by hiwelo** [jlengstorf/awesome-speaker-diversity#11]
Hi!
Great initiative.
You can maybe add the list of enbies speakers to your list?
The website is here: https://enbytech.github.io/.

Have a nice day 👍

**Comment by jlengstorf** [comment]
Hi, @hiwelo — this would be a great addition to the list! Would you be willing to open a pull request with the change?

The instructions for adding groups are here: https://github.com/jlengstorf/awesome-speaker-diversity/blob/master/README.md#please-add-your-group

Thank you!

**Comment by hiwelo** [comment]
Yes sure, I'll do this right now 👍
